module.exports = {
  apps: [
    {
      name: "trackgrab",
      script: "./server.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      restart_delay: 3000,
      max_memory_restart: "700M",
      // Allow the Node drain deadline and child cleanup to finish before PM2 kills it.
      kill_timeout: 960000,
      listen_timeout: 10000,
      time: true,
      env: {
        NODE_ENV: "production",
        PORT: "3001",
        MAX_CONCURRENT: "2",
        MAX_QUEUE: "30",
        DOWNLOAD_TIMEOUT_S: "900",
        DOWNLOAD_ATTEMPTS: "2",
        DOWNLOAD_RETRY_DELAY_MS: "2000",
        DOWNLOAD_QUEUE_TIMEOUT_S: "60",
        SHUTDOWN_GRACE_S: "930",
        YTDLP_FRAGMENTS: "4",
        CONVERT_MAX_MB: "500",
        CONVERT_CONCURRENCY: "1",
        CONVERT_TIMEOUT_S: "600",
        CONVERT_SOURCE_TIMEOUT_S: "180",
        CONVERT_ALLOWED_ORIGINS: "https://downloadscloudmp3.com",
        M4A_BITRATE: "128",
      },
    },
  ],
};
